%==========================================================================
% Driver for plotting the time evolution of the contours of the Allen-Cahn
% equation generated by 'Driver_ACE_RK4_ref_sol'.

% Created:     2023.01.09
% Last change: 2023.05.19

%   Mar 6, 2023:
%       Save as pdf instead of png format.
%   Mar 6, 2023:
%       Added lines of codes to save a transparent png version of the plot,
%       in order to generate the plot for the talk in the NCTS Spring Day.
%   Jan 29, 2023:
%       Added iters_to_plot. Changed colormap from 'jet' to 'turbo'. Added
%       piece of code to get rid of the white space around the MATLAB
%       figure.
%   Jan 9, 2023:
%       Created.
%==========================================================================

close all; clear; clc;

addpath( genpath('../export_fig-master') );

options_plot;

% Load the saved data:
load("ACE_ref_256x256_T25_dt0.0001.mat")

%--------------------------------------------------------------------------
gray3 = [ 0.255, 0.255, 0.255 ];
super_light_gray = [ 0.99, 0.99, 0.99 ];

% % Added on 2023.03.06:
% set( 0, 'DefaultAxesXColor', super_light_gray );
% set( 0, 'DefaultAxesYColor', super_light_gray );
% set( 0, 'DefaultAxesZColor', super_light_gray );
% set( 0, 'DefaultTextColor', super_light_gray );

%--------------------------------------------------------------------------
% Data
%--------------------------------------------------------------------------
% Spatial discretization:
Nx = 256;

Nt = size(t_hist,2);
dt = t_hist(2) - t_hist(1);

Ny = Nx;
Lx = 2*pi;
Ly = 2*pi;
hx = Lx/Nx;
hy = Ly/Ny;
x = linspace(-0.5*Lx+hx, 0.5*Lx, Nx+1); % !!!!!!!! Grazie JH !!!!!!!!
y = linspace(-0.5*Ly+hy, 0.5*Ly, Ny+1);
% x = linspace( 0, Lx, Nx);
% y = linspace( 0, Ly, Ny);
x = x(1:end-1); % !!!!!!!! Grazie JH !!!!!!!!
y = y(1:end-1);
[ xx , yy ] = ndgrid(x,y);

%--------------------------------------------------------------------------
% End of data
%--------------------------------------------------------------------------

% 2023.01.29: Array containing the iterations that we would like to plot
% and save to file:
iters_to_plot = [ 1, 6, 21, 36, 76, 151 ];


for iter=iters_to_plot

    [ ~, handle_cf ] = contourf( x, y, W_hist(:,:,iter), 100 );
    set( handle_cf, 'edgecolor', 'none' );
    axis equal
    colormap("parula");  % other nice options: 'jet', 'turbo', 'cool', 'parula'
    c = colorbar;
    %     caxis([-1, +1]);
    %     title(['Explicit RK4, iter ',num2str(iter-1),', time = ', num2str(dt*(iter-1))])
    set(c,'TickLabelInterpreter','latex')
    %----------------------------------------------------------------------
    % MS, 2023.03.06:
    % Change the color of the grid:
%     set( gca,'GridColor', super_light_gray )

    % Added on 2023.03.06:
    % Questo è il background "esterno" alla figura
%     set( gca,'Color', gray3 )
%     %----------------------------------------------------------------------
%     % Get rid of the large invisible border of the figure:
%     set(gca, 'units', 'normalized'); % Just making sure it's normalized
%     Tight = get(gca, 'TightInset');  % Gives you the bording spacing between plot box and any axis labels
%     % [Left Bottom Right Top] spacing
%     NewPos = [Tight(1) Tight(2) 1-Tight(1)-Tight(3) 1-Tight(2)-3*Tight(4)]; % New plot position [X Y W H]
%     set(gca, 'Position', NewPos);
%     %----------------------------------------------------------------------
    drawnow;

    %----------------------------------------------------------------------
    % SAVE IMAGE TO EPS FILE
    %----------------------------------------------------------------------
    fprintf('+--------------------------------------------------------------+\n');
    fprintf('|                           Save plot                          |\n');
    fprintf('+--------------------------------------------------------------+\n');
    fileName_plot = [ '../plots/ACE_RK4_ref_sol_time_', num2str(dt*(iter-1)) ];

    set(gcf, 'Color', 'w');
%     % Save plot to eps file
%     saveas( gcf, fileName_plot, 'epsc' )
%     % exportgraphics( gca, fileName_plot, 'BackgroundColor', 'none' )
%     fprintf('Saved graph to file %s.eps.\n', fileName_plot);

    %--------------------------------------------------------------------------
    % Save plot to png file
    export_fig(fileName_plot, '-dpng', '-transparent', '-r300'); % -r300 is the PPI value, default resolution is low
    % export_fig(fileName_plot, '-pdf', '-opengl','-r600');
    fprintf('Saved graph to file %s.pdf.\n', fileName_plot);
    %--------------------------------------------------------------------------
    pause(0.1)

end


