%==========================================================================
% Driver for plotting the time evolution of the discrete L2 norm of the
% right-hand side of the Allen-Cahn equation generated by
% 'Driver_ACE_RK4_ref_sol'.

% Created:     2022.12.31
% Last change: 2023.01.10

%   Jan 10, 2023:
%       Added solution with the CFD discretization of the Laplacian.
%   Dec 31, 2022:
%       Created.
%==========================================================================

close all; clear; clc;

options_plot;

% Load the saved data:
load("ACE_ref_256x256_T15_dt0.0001.mat")

%--------------------------------------------------------------------------
% Data
%--------------------------------------------------------------------------
% Spatial discretization:
Nx = 256;
Lx = 2*pi;

hx = Lx/Nx;
Nt = length(t_hist);

epsilon = 0.1; % value used in the paper of Rodgers and Venturi.

% 2) The discretized 1D Laplacian in sparse format:
A = -(1/hx^2) * get_Ah( Nx );

%--------------------------------------------------------------------------
% End of data
%--------------------------------------------------------------------------

for i=1:Nt
    L2_norm_RHS(i) = norm( get_RHS( W_hist(:,:,i), A, epsilon ), 'fro' ) * hx;
    rank_W_hist(i) = rank( W_hist(:,:,i) );
end

%--------------------------------------------------------------------------
% Plot
figure(1)
semilogy( t_hist, L2_norm_RHS, "Color", blue, "LineStyle", "-", "LineWidth", 2 )
hold on
grid on
xlabel('$t$')
ylabel('$\| \partial w / \partial t \|_{L^{2}(\Omega)}$')
% xlim( [ 10, 15 ] )
ylim( [ 1e-5 10 ] )


%--------------------------------------------------------------------------
% SAVE IMAGE TO EPS FILE
%--------------------------------------------------------------------------
fprintf('+--------------------------------------------------------------+\n');
fprintf('|                           Save plot                          |\n');
fprintf('+--------------------------------------------------------------+\n');
fileName_plot = '../plots/ACE_RK4_ref_sol_L2_norm_vs_time';

set(gcf, 'Color', 'w');
export_fig(fileName_plot, '-pdf', '-opengl','-r600');

% Save plot to eps file
saveas( gcf, fileName_plot, 'epsc' )
fprintf('Saved graph to file %s.pdf.\n', fileName_plot);


%--------------------------------------------------------------------------
% Plot
figure(2)
semilogy( t_hist, rank_W_hist, "Color", red, "LineStyle", "-", "LineWidth", 2 )
hold on
grid on
xlabel('$t$')
ylabel('$ \mathrm{rank}(W_{\mathrm{ref}}) $')
% xlim( [ 0, 3 ] )
% ylim( [ 12 18 ] )


%--------------------------------------------------------------------------
% SAVE IMAGE TO EPS FILE
%--------------------------------------------------------------------------
fprintf('+--------------------------------------------------------------+\n');
fprintf('|                           Save plot                          |\n');
fprintf('+--------------------------------------------------------------+\n');
fileName_plot = '../plots/ACE_RK4_ref_sol_rank_vs_time';

set(gcf, 'Color', 'w');
export_fig(fileName_plot, '-pdf', '-opengl','-r600');

% Save plot to eps file
% saveas( gcf, fileName_plot, 'epsc' )
fprintf('Saved graph to file %s.pdf.\n', fileName_plot);
